### ISSUE TITLE
Guile-gi does not install in the latest stable version of Guile

### ISSUE THREAD

**Issue by jamescrake-merani** [spk121/guile-gi#129]
Unlike most other modules I use, guile-gi does not seem to install in the latest stable version of Guile on my machine. I am running on Arch Linux meaning I have to have two version of guile installed: 2.2, and 3.0. This is because 3.0 is not in the official Arch Linux so I have to install guile3 from the AUR but I still need to keep guile2 in order to satisfy dependencies.

I am not familiar with how autotools work but I have noticed that most modules have an `m4` directory containing a `guile.m4` file where `GUILE_EFFECTIVE_VERSION` seems to be set. However, in this repository there seems to be no `guile.m4` file.

**Comment by LordYuuma** [comment]
The `guile.m4` file is part of Guile's distribution and should thus be included in the guile3 AUR package. IIUC, the problem is that your guile2.2 installation appears to be taking precedence – thus, guile-gi will be configured for guile-2.2. Thus, if you want guile-3.0, you should arrange it so that it shadows guile-2.2 as you're running configure.
