### ISSUE TITLE
Implement structure/union field getters and setters

### ISSUE THREAD

**Issue by spk121** [spk121/guile-gi#28]
There is the uncommon case of wanting to access the structure/union fields via getters/setters instead of introspected methods.  Some gstruct provide a list of `GIFieldInfo *` that can be used to get/set fields directly.

Since it is uncommon, a half measure would be just to merge `g_struct_info_find_field` and `g_field_info_{set,get}_field` into some sort of `(struct-set! obj fieldname val)`

To be more complete, we could make slot accessors in the type's GOOPS class.

**Comment by LordYuuma** [comment]
I'm pretty sure that getters and setters would be introspected methods. In the case, where such methods are not exported, the alternative is to directly access the field itself by offset and I'm pretty sure `GIFieldInfo` does that.

We have a few problems, if we use your approach. First,  `g_field_info_{set,get}_field` does not work for fields of composite types, where we would have to figure something out ourselves. Second, it would require `GIArguments`, which would mean creating an argmap and everything. On the property side we handle everything with `GValue`s, meaning property code and field code would do vastly different things for the same operation, which is weird to say the least.

On the other hand, we can define a `<field>` type analogous to the `<signal>` type that we already have and fill it with relevant information from the FieldInfo. That field would be an applicable struct with a setter much like properties are and the internals can do whatever. However, here too we have a few smaller issues, especially w.r.t. GITransfer.

**Comment by LordYuuma** [comment]
By the way, is there an "easy" or straightforward way of resolving `GITypeInfo`s to a `GType` and a set of flags? I believe we vaguely do something along those lines when constructing ArgMaps or implicitly rely on a 1:1 mapping of e.g. GI_TYPE_TAG_INT32 <-> G_TYPE_INT. Tbh. it is quite weird in the first place, that GI has to do their own stuff and can neither reuse Values nor Variants.

**Comment by spk121** [comment]
As far as I know, there is no straightforward way to do that.  In the gobject introspection code itself, the structs are somewhat obfuscated.  It can be done -- mostly it is in GIR's `gitypelib-internal.h` file -- but, it would take a little effort to untangle it from GIR.

**Comment by LordYuuma** [comment]
I don't think we should rely on implementation details, that sounds like it would break a lot. The reason I'm bringing this up, is because it would be helpful in multiple areas of our code where we need to rely on `GType`s. First, we need this kind of information when setting up specializers, second we would need it here if we wanted to do something `GValue`-based. I'm also playing with the idea of reusing ParamSpecs for fields, which would allow us to reuse some of the code that we've written for properties, although we would still need to write actual getters and setters from `GValue`s.

**Comment by spk121** [comment]
I guess there are at least 5 variant datatypes that will eventually have to convert to SCM
- GIArgInfo + GIArgument
- GITypeInfo + GIArgument
- GValue
- GType + something
- GVariant (read-only once created)

In terms of flexibility it is approx
SCM > GIArgInfo > GITypeInfo > GType > GVariant > GValue.
It does seem like an unnecessary amount of variant datatypes.

**Comment by LordYuuma** [comment]
I think GType + something should actually be equal to GValue unless that something contains additional information. GValue contains about as much type information as an SCM, the only difference is that there is no GType for lists (i.e. GLists, I'm pretty sure you could store GeeLists or whatever just fine) or pairs. However, that aside I believe one could easily build a Scheme interpreter that runs on GValue alone.

GVariant is even more restrictive w.r.t. types, but offers more convenience upon creation with its many constructors and builders. GITypeInfo fills some holes in GType that really shouldn't exist (using TypeTags rather than GType is an ugly hack), but also contains some additional information, such as whether something is a pointer or not. GIArgInfo additionally gives us memory management hints as well as relations to other arguments.

**Comment by spk121** [comment]
One could make a build where you move to GType + flags ASAP in the arg map, avoiding storing introspection-related types like GITypeInfo, GIArgInfo, GIInfoType. I could take a stab at it, if you haven't done it already.

**Comment by LordYuuma** [comment]
I haven't yet. FieldInfos seem a lot more tedious than properties, so I'd try to resolve everything tagged `0.1 release` first so that we can have a proper release before doing some of the more experimental stuff. That said, we can already lay the groundwork as long as it stays trivially rebaseable w.r.t. master.

**Comment by LordYuuma** [comment]
Are fields still relevant? This issue was opened before #43, in which we've decided to drop any support whatsoever for untyped structures. Structues with a GType are much more likely to have accessor functions and fields without accessors are probably not expected to be accessed – such as `object:ref-count`.

**Comment by spk121** [comment]
I've been trying to write some code in gtk, following the standard examples.  I feel confident structure accessors would be seldom used.

**Comment by LordYuuma** [comment]
Okay. Let's leave this open a little while longer and perhaps collect examples, in which fields need to be used.
