### ISSUE TITLE
guile-gi in Guix (apparently) unable to find libguile-gi

### ISSUE THREAD

**Issue by dannyob** [spk121/guile-gi#72]
Hi! I'm very excited to play around wit guile-gi, but I'm having some problems getting it to work on guix. After package installing guile-gi, I get this error:

```
% guile
GNU Guile 2.2.6
Copyright (C) 1995-2019 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> (use-modules (gi))
While compiling expression:
In procedure dynamic-link: file: "libguile-gi", message: "file not found"
scheme@(guile-user)> 
```
Some more info that may be useful:
```
% env | grep '\(GUILE\|LIB\|GTK\)' 
GTK_DATA_PREFIX=/run/current-system/profile
GUILE_LOAD_PATH=/home/danny/.guix-profile/share/guile/site/2.2:/run/current-system/profile/share/guile/site/2.2
GI_TYPELIB_PATH=/home/danny/.guix-profile/lib/girepository-1.0
GUILE_LOAD_COMPILED_PATH=/home/danny/.guix-profile/lib/guile/2.2/site-ccache:/run/current-system/profile/lib/guile/2.2/site-ccache
GUIX_GTK3_PATH=/home/danny/.guix-profile/lib/gtk-3.0:/run/current-syste
```
```
%; find ~/.guix-profile/ -name "*libguile-gi*"
/home/danny/.guix-profile/lib/guile/2.2/libguile-gi.so
/home/danny/.guix-profile/lib/guile/2.2/libguile-gi.so.4.0.0
/home/danny/.guix-profile/lib/guile/2.2/libguile-gi.la
/home/danny/.guix-profile/lib/guile/2.2/libguile-gi.so.4
```

**Comment by spk121** [comment]
Well, the workaround is to set the `GUILE_SYSTEM_EXTENSIONS_PATH` environment variable to the location where libguile-gi.so lives.
But the more interesting question is where guile thinks that the extensions should have been installed.  What do you get when you run `pkg-config guile-2.2 --variable=extensiondir` ?
`

**Comment by LordYuuma** [comment]
I don't think, querying `pkg-config` for such paths is a great idea in Guix.  Either way, this is a bug in Guix upstream.  The guile-gi command from our package circumvents it by patching `LD_LIBRARY_PATH`.

The real bug here is, that guile lacks a native-search-path for `GUILE_SYSTEM_EXTENSION_PATH`.  I'd suggest "lib/guile/@GUILE_VERSION@/extensions".  We should adjust our build to put them into the extensions subdirectory, however, as that's what guile-readline,guile-gnutls et al. already do.

**Comment by spk121** [comment]
Looks good to me

**Comment by spk121** [comment]
@dannyob are you able to verify if the patches @LordYuuma made on current master solves your problem? It looks right, but I don't have a working Guix to test it on at the moment.

**Comment by LordYuuma** [comment]
My patches alone can't fix this.  As I've already pointed out, you'd need a native-search-path for `GUILE_SYSTEM_EXTENSION_PATH`, which Guix currently has not – altenatively, you can install guile-gi system-wide if you really want to – and the guile-gi package shipped in Guix would also need to be adjusted.  I'm surprised their recipe even works, there's some high level magic going on in Berlin as far as I can see.

**Comment by LordYuuma** [comment]
Update: I just found out, that other libraries are patched before compilation to use the full path of the extension they load.  However, this solution does not apply to guile-gi, because we need to (as far as I know) load the introspection library already at compile time.  Is there a way around this or are we doomed?

**Comment by spk121** [comment]
In `libguile/dynl.c`, `system_extensions_path` is initialized first to the compiled extensions path as a fallback, or the GUILE_SYSTEM_EXTENSION_PATH environment variable.  And the `dynamic-link` procedure does have some unused capability for `system_extensions_path` to have multiple entries.

I think we can fix this in core Guile by adding procedures to query and update `system_extensions_path` in `libguile/dynl.c`, the way you can adjust `%load-path` in `load.c` you can now.

**Comment by LordYuuma** [comment]
We can already "load" libguile-gi at runtime either way.  The problem is, that we "have to" load our extension in advance for some variables and procedures to be bound.  We can do without that if we don't mind warnings.  In Guix we'd have to then build, install and check in that order, since we can't run check without the files being installed if we use this method.  A common pattern IIRC.

**Comment by LordYuuma** [comment]
The recipe in 68a928dc80306c37bf7f7780730f025497c398de should work exactly as intended, the only difference being the source (local checkout versus tarball) and the somewhat non-descriptive version field.  I suggest updating Guix upstream accordingly unless you want to come up with a better solution.

**Comment by spk121** [comment]
Well, looking at your solution, I think I finally understand the original question.  I don't have much experience with Guix.
