### ISSUE TITLE
current guix package doesn't seem to work

### ISSUE THREAD

**Issue by dannyob** [spk121/guile-gi#84]
Hi! Not having much luck with the current version of guile-gi on Guix:

```
% guix package --list-installed=guile-gi
guile-gi	0.3.0	out	/gnu/store/rxdlnjmxadglpwhymprfav0jnk6bllyr-guile-gi-0.3.0
% guile
GNU Guile 3.0.2
[...]
scheme@(guile-user)> (use-modules (gi))
While compiling expression:
In procedure dynamic-link: file: "/gnu/store/rxdlnjmxadglpwhymprfav0jnk6bllyr-guile-gi-0.3.0/lib/guile/3.0/libguile-gi", message: "file not found"
```

**Comment by LordYuuma** [comment]
This Guix package is not maintained by us and there have been quite a few issues with it historically.  We do keep our own `guix.scm` for exactly that reason, but it has been a while since the last commit to this repo and we are not up to date with Guix' switch to Guile 3.

I've traced this error locally, and it seems the Guix maintainers missed, that we're now installing to `$prefix/lib/guile/$EFFECTIVE_VERSION/extensions`.

**Comment by LordYuuma** [comment]
After closer investigation, our `guix.scm` still works.  I think this error be better reported to the Guix mailing lists.

**Comment by dannyob** [comment]
Thanks, I'll look to that!
